### ISSUE TITLE
Enforce or disallow spaces inside of curly braces in JSX attributes

### ISSUE THREAD

**Issue by pablosichert** [One-com/eslint-config-onelint#18]
Regarding curly braces for JSX attributes - suggesting to decide for either allowing only exactly

``` jsx
<Hello name={ firstname } />;
```

or only exactly

``` jsx
<Hello name={firstname} />;
```

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md

**Comment by gustavnikolaj** [comment]
This will probably require us to make a eslint-config-onelint-react module. I suspect that you need to use babel-eslint in order to parse JSX, and I don't want that to be a requirement for other consumers of this module.

We can use the extend syntax to extend the react config we use at the moment. http://eslint.org/docs/user-guide/configuring#extending-configuration-files

**Comment by gustavnikolaj** [comment]
Due to eslint-config-standard-react beginning to get more standard-like in recent versions I had to create our own react config. See https://github.com/One-com/eslint-config-onelint-react.

I moved the issue there: https://github.com/One-com/eslint-config-onelint-react/issues/2
